name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v1
    - name: Archlinux CMake builder
      uses: codehz/arch-cmake-builder@v0.1
    - name: configure build
      run: cmake . -G Ninja
    - name: build
      run: ninja
